# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-20 00:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='age',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
