"""empty message

Revision ID: b72767ae6846
Revises: 99bb6bbb5e28
Create Date: 2018-05-12 22:32:49.124108

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b72767ae6846'
down_revision = '99bb6bbb5e28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('email', table_name='users')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', mysql.VARCHAR(length=120), nullable=False))
    op.create_index('email', 'users', ['email'], unique=True)
    # ### end Alembic commands ###
